config/routes.rb
LearnCreative::Application.routes.draw do

  devise_for :members

  root :to => 'pages#home'

  get 'videos/library'

  get 'subjects/list'

  get 'videos/:id' => 'videos#show'

  get 'videos/:id/edit' => 'videos#edit'

  post 'videos/:id/' => 'videos#create'

  post 'videos/:id/' => 'videos#update'

  post 'videos/:id/' => 'videos#delete'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :videos

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :subject


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def list
    @subjects = Subject.order('subjects.position ASC')
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  before_filter :authenticate_member!

  def library

    @videos = Video.order('videos.position ASC')

    @art_videos         = @videos.select { |video| video.subject.name == 'Art' }
    @graphic_videos     = @videos.select { |video| video.subject.name == 'Graphics' }
    @web_videos         = @videos.select { |video| video.subject.name == 'Web' }
    @development_videos = @videos.select { |video| video.subject.name == 'Development' }
    @business_videos    = @videos.select { |video| video.subject.name == 'Business' }

  end

  def show
    @video = Video.find(params[:id])
  end

  def edit
    @video = Video.find(params[:id])
  end

  def create
    @video = Video.new(params[:title], params[:subject])
    if @video.save
      redirect_to(:action => 'library')
    end
      render('new')
  end

  def update
    @video = Video.find(params[:id])
    @video = @video.update_attributes(title: params[:title])

    # error says: cannot find update_attributes
    #@video.update_attributes(title: params[:title])
  end

  def delete
    @video = Video.find(params[:id]).destroy

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/videos_controller_helper.rb
module VideosControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Learn Creative</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="css/custom.css">
  <link href='http://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

</head>
<body>

<header>
  <div class="row">
    <div class="large-3 columns">
      <a href="<%= root_path %>">
        <h2 class="logo"><%= image_tag('logo.png') %></h2>
      </a>

    </div>
    <div class="large-9 columns">
      <ul class="right inline-list">

       <% if member_signed_in?  %>

        <li><a class="navLink" href="<%= '/videos/library' %>">Library</a></li>

        <li>
            <%= link_to 'Sign out', destroy_member_session_path, :method => :delete, :class => 'navLink' %>
        </li>

        <% else %>

        <li><a class="navLink" href="<%= '/members/sign_in' %>">Sign in</a></li>

        <li><a class="button buttonsignup success-dark radius" href="<%= '/members/sign_up' %>">Sign up</a></li>

        <% end %>


      </ul>
    </div><!-- navigation -->
  </div><!-- row -->
</header><!-- End Header and Nav -->



<%= yield %>


    <!-- Footer -->
<footer>
    <div class="row">


      <div class="large-3 columns">
        <a href="<%= root_path %>">
          <h2 class="logo"><%= image_tag('logo.png') %></h2>
        </a>
      </div>

      <div class="large-3">
        <br/>
      </div>

      <div class="large-4 columns copyright">
        <p class="right green">Copyright &copy; 2013 by Enok.Madrid &nbsp;&nbsp;&nbsp;&nbsp;</p>
      </div>


    </div><!-- row -->
</footer><!-- Footer -->

</body>
</html>

app/views/pages/home.html.erb
<!-- Home CTA -->
<section class="cta">

  <div class="row">

    <!-- cta -->
    <div class="large-6 columns">
      <br />
      <h1>A place to learn and build creative skills</h1>
      <br />
      <h4>Learn how to draw, how to design, make websites, dive into web programming and even learn how to start a business.</h4>
      <br />

      <% if member_signed_in? %>
        <li><a class="button success-dark radius signup" href="<%= '/videos/library' %>">Start learning now</a></li>
      <% else %>
        <li><a class="button success-dark radius signup" href="<%= '/members/sign_up' %>">Start learning now</a></li>
      <% end %>

      <br />
    </div>


    <!-- cartoon -->
    <div class="large-6 columns">
      <span class="right cartoon"><%= image_tag('cartoon.png') %></span>
    </div>

  </div><!-- row -->

</section>






<!-- Subjects CTA -->
<section class="subjects">
  <div class="row">
    <br />
    <br />

    <!-- cta -->
    <div class="subject panel large-3 columns">
      <h5>Drawing and Coloring</h5>
      <br />
      <p>I will teach you drawing, coloring, painting, and the important fundamentals of art.</p>
    </div>
    <div class="subject panel large-3 columns">
      <h5>Graphic Design</h5>
      <br />
      <p>Then we'll explore creativity with software tools like Photoshop and Illustrator</p>
    </div>
    <div class="subject panel large-3 columns">
      <h5>Web Design &amp; Code</h5>
      <br />
      <p>You'll then create for the web using HTML5, CSS, and server-side languages.</p>
    </div>
    <div class="subject panel large-3 columns">
      <h5>Business Skills</h5>
      <br />
      <p>Finally, with these skills, I'll teach you how to sell yourself and launch your own business.</p>
    </div>
  </div><!-- row -->


  <div class="row">
    <div class="large-3 columns right">
      <% if member_signed_in? %>
        <li><a class="button success-dark radius right teach" href="<%= '/videos/library' %>">Let's Go!</a></li>
      <% else %>
        <li><a class="button success-dark radius right teach" href="<%= '/members/sign_up' %>">Teach me now!</a></li>
      <% end %>
    </div>
  </div>

</section>

app/views/subjects/list.html.erb
<div class="row">

  <div class="large-12 columns">
    <h2 class="center">Subjects</h2>
    <br/>

    <table class="listing" summary="Subject List">

      <tr>
        <th>&nbsp;</th>
        <th>Subject</th>
        <th>Visible</th>
        <th>Actions</th>
      </tr>

      <% @subjects.each do |subject| %>

      <tr>
        <td><% subject.position %></td>
        <td><% subject.name %></td>
        <td><%= subject.visible ? 'Yes' : 'No' %></td>
        <td class="actions">
          <%= link_to('Show', {:action => 'list', :id => subject.id}, :class => 'action show')   %>

        </td>
      </tr>

      <% end %>

    </table>

  </div>

</div>

app/views/videos/edit.html.erb
<!-- ====== EDIT FORM: VIDEO TITLE ====== -->
<section class="loginform">

  <div class="row">

    <div class="large-6 large-centered columns">

        <form class="login" method="post" action="/videos/<%= @video.id %>">
          <fieldset class="login">
            <p>Current Title:</p>
            <h3><%= @video.title %></h3><br/>

            <div class="row collapse">
              <div class="small-9 columns">
                <input type="text" placeholder="Enter new title here"/>
              </div>
              <div class="small-3 columns">
                <input class="button postfix success-dark radius" type="submit" value="Submit"/>
              </div>
            </div>

          </fieldset>
        </form>

    </div>

  </div>
</section>

app/views/videos/home.html.erb
<!-- Home CTA -->
<section class="cta">

  <div class="row">

    <!-- cta -->
    <div class="large-6 columns">
      <br />
      <h1>A place to learn and build creative skills</h1>
      <br />
      <h4>Learn how to draw, how to design, make websites, dive into web programming and even learn how to start a business.</h4>
      <br />
      <li><a class="button success-dark radius signup" href="<%= '/members/sign_up' %>">Start learning now</a></li>
      <br />
    </div>


    <!-- cartoon -->
    <div class="large-6 columns">
      <span class="right cartoon"><%= image_tag('cartoon.png') %></span>
    </div>

  </div><!-- row -->

</section>






<!-- Subjects CTA -->
<section class="subjects">
  <div class="row">
    <br />
    <br />

    <!-- cta -->
    <div class="subject panel large-3 columns">
      <h5>Drawing and Coloring</h5>
      <br />
      <p>I will teach you drawing, coloring, painting, and the important fundamentals of art.</p>
    </div>
    <div class="subject panel large-3 columns">
      <h5>Graphic Design</h5>
      <br />
      <p>Then we'll explore creativity with software tools like Photoshop and Illustrator</p>
    </div>
    <div class="subject panel large-3 columns">
      <h5>Web Design &amp; Code</h5>
      <br />
      <p>You'll then create for the web using HTML5, CSS, and server-side languages.</p>
    </div>
    <div class="subject panel large-3 columns">
      <h5>Business Skills</h5>
      <br />
      <p>Finally, with these skills, I'll teach you how to sell yourself and launch your own business.</p>
    </div>
  </div><!-- row -->


  <div class="row">
    <div class="large-3 columns right">
      <li><a class="button success-dark radius right teach" href="<%= '/members/sign_up' %>">Teach me now!</a></li>
    </div>
  </div>

</section>

app/views/videos/library.html.erb
<section class="library" xmlns="http://www.w3.org/1999/html">

<div class="row">
  <div class="large-8 columns"></div>
  <div class="large-4 columns"><p class="email">Signed in as <span><a href="/members/edit"> <%= current_member.email %></a></span></p></div>
</div>

<!-- ======== Art ======== -->
  <div class="row"><br/><br/>

    <div class="large-12 columns">
      <h2>Art Videos</h2>
    </div>

    <!-- displays all art videos -->
    <% @art_videos.each do |video| %>
    <div class="subject panel large-3 columns">
      <a class="text-center" href=<%= "/videos/#{video.id}" %>>
        <p>
          <%= image_tag( 'play.png', :class => 'icons' ) %>
        </p>
        <h6><%= video.title %></h6></a>
    </div>
    <% end %>

  </div><br/><hr>
<!-- ====== end art ====== -->

<!-- ======== Graphics ======== -->
  <div class="row"><br/><br/>

    <div class="large-12 columns">
      <h2>Graphics Videos</h2>
    </div>

    <!-- displays all art videos -->
    <% @graphic_videos.each do |video| %>
        <div class="subject panel large-3 columns">
          <a class="text-center" href=<%= "/videos/#{video.id}" %>>
          <p>
            <%= image_tag( 'play.png', :class => 'icons' ) %>
          </p>
          <h6><%= video.title %></h6></a>
        </div>
    <% end %>

  </div><br/><hr>
<!-- ====== end graphics ====== -->

<!-- ======== Web ======== -->
  <div class="row"><br/><br/>

    <div class="large-12 columns">
      <h2>Web Videos</h2>
    </div>

    <!-- displays all art videos -->
    <% @web_videos.each do |video| %>
        <div class="subject panel large-3 columns">
          <a class="text-center" href=<%= "/videos/#{video.id}" %>>
            <p>
              <%= image_tag( 'play.png', :class => 'icons' ) %>
            </p>
            <h6><%= video.title %></h6></a>
        </div>
    <% end %>

  </div><br/><hr>
<!-- ====== end web ====== -->

<!-- ==== Development ==== -->
  <div class="row"><br/><br/>

    <div class="large-12 columns">
      <h2>Development Videos</h2>
    </div>

    <!-- displays all art videos -->
    <% @development_videos.each do |video| %>
        <div class="subject panel large-3 columns">
          <a class="text-center" href=<%= "/videos/#{video.id}" %>>
            <p>
              <%= image_tag( 'play.png', :class => 'icons' ) %>
            </p>
            <h6><%= video.title %></h6></a>
        </div>
    <% end %>

  </div><br/><hr>
<!-- === end development === -->

<!-- ==== Business ==== -->
  <div class="row"><br/><br/>

    <div class="large-12 columns">
      <h2>Business Videos</h2>
    </div>

    <!-- displays all art videos -->
    <% @business_videos.each do |video| %>
        <div class="subject panel large-3 columns">
          <a class="text-center" href=<%= "/videos/#{video.id}" %>>
            <p>
              <%= image_tag( 'play.png', :class => 'icons' ) %>
            </p>
            <h6><%= video.title %></h6></a>
        </div>
    <% end %>

  </div><br/><br/>
<!-- === end business === -->

</section>





<section class="create">
<div class="row">
  <div class="large-6 large-centered columns formpadding">

  <br/><br/><br/><br/><br/>
  <h4>Want to create a new video?</h4>
  <form action="/videos/create" method="post" >

    <div class="row collapse">
        <div class="large-9 columns">
            <input type="text" name="video[title]" placeholder="Title of New Video"/>
        </div>
        <div class="large-3 columns">
          <div id="customDropdown" class="small secondary radius">
            <select>
              <option>Art</option>
              <option>Graphics</option>
              <option>Web</option>
              <option>Development</option>
              <option>Business</option>
            </select>
          </div>
        </div>
    </div>

    <input class="button small success-dark radius" type="submit" value="Add Video"/>

  </form>


  </div>
</div>
</section>

app/views/videos/show.html.erb
<section class="library">
  <div class="row">

    <div class="large-12 columns vid">
      <br/>
      <h1><%= @video.title %></h1>
    </div>

  </div>

  <div class="row">

    <div class="large-12 large-centered columns">
      <div class="panel">

        <%= video_tag 'learn_creative.webm', :size => '930x523', :poster => 'video.png', :controls => true %>

      </div>

    </div>

  </div>

  <div class="row">
        <div class="large-3 columns">
          <a href="<%= '/videos/library' %>" class="button small success-dark radius crud">Back to Library</a>
        </div>
        <div class="large-5 columns">
          <p class="right"><%= @video.title %><strong>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            Subject: &nbsp; &nbsp;</strong><%= @video.subject.name %></p>
        </div>

        <div class="large-4 columns right">
          <div class="row collapse">
            <form class="large-9 columns" method="post" action=<%= "/videos/#{@video.id}/edit" %>>
                <a href="<%= "/videos/#{@video.id}/edit" %>" class="button small secondary radius crud right">Edit</a>
            </form>
            <form class="large-3 columns" method="post" action=<%= "/videos/#{@video.id}/delete" %>>
                <input class="button small alert-dark radius crud right" type="submit" value="Delete" name="delete">
            </form>
          </div>
        </div>
  </div>
  <br/><br/><br/>
</section>